assert(type(log) == "table", "The log builtin should be available")
assert(type(log.event) == "function", "Should support logging messages with severity EVENT")
assert(type(log.test) == "function", "Should support logging messages with severity TEST")
assert(type(log.debug) == "function", "Should support logging messages with severity DEBUG")
assert(type(log.info) == "function", "Should support logging messages with severity INFO")
assert(type(log.notice) == "function", "Should support logging messages with severity NOTICE")
assert(type(log.warning) == "function", "Should support logging messages with severity WARNING")
assert(type(log.error) == "function", "Should support logging messages with severity ERROR")
assert(type(log.critical) == "function", "Should support logging messages with severity CRITICAL")
assert(type(log.alert) == "function", "Should support logging messages with severity ALERT")
assert(type(log.emergency) == "function", "Should support logging messages with severity EMERGENCY")

assert(log.event == _G.EVENT, "Should export global EVENT")
assert(log.test == _G.TEST, "Should export global TEST")
assert(log.debug == _G.DEBUG, "Should export global DEBUG")
assert(log.info == _G.INFO, "Should export global INFO")
assert(log.notice == _G.NOTICE, "Should export global NOTICE")
assert(log.warning == _G.WARNING, "Should export global WARNING")
assert(log.error == _G.ERROR, "Should export global ERROR")
assert(log.critical == _G.CRITICAL, "Should export global CRITICAL")
assert(log.alert == _G.ALERT, "Should export global ALERT")
assert(log.emergency == _G.EMERGENCY, "Should export global EMERGENCY")

print("OK\tBuiltins\tlog")